version: '3'
services:
  v80:
    build:
      context: .
      dockerfile: Dockerfile.80
    volumes:
      - ../:/app:rw
      - ./var/.coverage:/opt/phpstorm-coverage/:rw
    container_name: php-dev-v80
    tty: true
  v81:
    build:
      context: .
      dockerfile: Dockerfile.81
    volumes:
      - ../:/app:rw
      - ./var/.coverage:/opt/phpstorm-coverage/:rw
    container_name: php-dev-v81
    tty: true
  v82:
    build:
      context: .
      dockerfile: Dockerfile.82
    volumes:
      - ../:/app:rw
      - ./var/.coverage:/opt/phpstorm-coverage/:rw
    container_name: php-dev-v82
    tty: true